### ISSUE TITLE
App crashes when opening database via CCTG share

### ISSUE THREAD

**Issue by ekordas** [mh-/corona-warn-companion-android#131]
Reproduktion:
Export database from CCTG
Share to corona-warn-companion
> App lounches, displays wihte screen and App was closed Dialog appears

Device: BQ Aquaris M5
lineage-os 17.1-20190126-NIGHTLY-piccolo (Android 7.1.2)

logcat (exert, ask if you need the full log):
```
11-21 18:19:33.564 30117 30117 D MicroGDbOnDisk: Scan read: a68f4d11d392ac0c9067780bc6950c43 cfda5a3b RSSI: -100, Timestamp: 1637515063028, Duration: 0
11-21 18:19:33.565 30117 30117 D MicroGDbOnDisk: Successfully parsed microG database.
11-21 18:19:33.600   814   913 I ActivityManager: Killing 26496:com.github.axet.maps/u0a149 (adj 906): empty #17
11-21 18:19:33.627   256   256 I MSM-irqbalance: Decided to move IRQ178 from CPU5 to CPU4
11-21 18:19:33.671   814   913 W WindowManager: Attempted to add a toast window with unknown token android.os.Binder@928505b.  Aborting.
11-21 18:19:33.676 30117 30117 D AndroidRuntime: Shutting down VM
11-21 18:19:33.679 30117 30117 E AndroidRuntime: FATAL EXCEPTION: main
11-21 18:19:33.679 30117 30117 E AndroidRuntime: Process: org.tosl.coronawarncompanion, PID: 30117
11-21 18:19:33.679 30117 30117 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@9ebf38d is not valid; is your activity running?
11-21 18:19:33.679 30117 30117 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
11-21 18:19:33.679 30117 30117 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
11-21 18:19:33.679 30117 30117 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
11-21 18:19:33.679 30117 30117 E AndroidRuntime: 	at android.widget.Toast$TN.handleShow(Toast.java:459)
11-21 18:19:33.679 30117 30117 E AndroidRuntime: 	at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
11-21 18:19:33.679 30117 30117 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-21 18:19:33.679 30117 30117 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-21 18:19:33.679 30117 30117 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
11-21 18:19:33.679 30117 30117 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-21 18:19:33.679 30117 30117 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-21 18:19:33.679 30117 30117 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
11-21 18:19:33.685   814 19053 W ActivityManager:   Force finishing activity org.tosl.coronawarncompanion/.MainActivity
11-21 18:19:33.690   814 19053 W ActivityManager:   Force finishing activity org.tosl.coronawarncompanion/.MainActivity
11-21 18:19:33.691   814 19053 W ActivityManager: Duplicate finish request for ActivityRecord{b44f7dc u0 org.tosl.coronawarncompanion/.MainActivity t38555 f}
11-21 18:19:33.724   814  3128 D ActivityManager: cleanUpApplicationRecord -- 26496
11-21 18:19:33.771   814  8451 I OpenGLRenderer: Initialized EGL, version 1.4
11-21 18:19:33.771   814  8451 D OpenGLRenderer: Swap behavior 1
11-21 18:19:34.191   814  1058 W ActivityManager: Activity pause timeout for ActivityRecord{b44f7dc u0 org.tosl.coronawarncompanion/.MainActivity t38555 f}
11-21 18:19:34.196   814  1058 I WindowManager: Failed to capture screenshot of Token{ac0e5 ActivityRecord{b44f7dc u0 org.tosl.coronawarncompanion/.MainActivity t38555 f}} appWin=Window{bd5e412 u0 Starting org.tosl.coronawarncompanion} drawState=4

```

**Comment by skyerjoe** [comment]
Does it occur after an os update?
If so try to level up the permissions for cctg and cwc. 

And ur infos about ur settings ( phone, os etc.) is to weak.
Best regards

**Comment by mh-** [comment]
I cannot reproduce this here, but I also don't have this setup (lineage os, etc).
Is this maybe a memory problem, i.e. an extremely large database?

**Comment by ekordas** [comment]
I closed all background apps. Still crashing. Acording to the Active Services Tab in the Developer Options I had 1.7GB of free Ram. The app uses about 20mb during the Import(Acording to that dialog)
Here is an db export from my cctg: 
[exposure.zip](https://github.com/mh-/corona-warn-companion-android/files/7598971/exposure.zip)
( Does exposure.db contains sensitive data? Please delete if so.)
I can help with some tests if you give me a direction. I have adb set up, but dont know what to do. I just began Android development.

**Comment by wurstsalat3000** [comment]
Updating to 2.1.3 seems to have solved the problem (thanks to heap size adjustment, I guess). German user here. Thanks a lot!
