### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Romern** [mh-/corona-warn-companion-android#147]
When I start the app, it sais that it downloads the keys for a couple seconds, and crashes with:

`FATAL EXCEPTION: main
Process: org.tosl.coronawarncompanion, PID: 31994
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.OutOfMemoryError: Failed to allocate a 7292936 byte allocation with 5931296 free bytes and 5792KB until OOM, target footprint 268435456, growth limit 268435456
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:126)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 7292936 byte allocation with 5931296 free bytes and 5792KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.ArrayList.grow(ArrayList.java:275)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
	at java.util.ArrayList.add(ArrayList.java:467)
	at j$.util.stream.-$$Lambda$I4culQbRd0-rjXdb6TS5OWvOlKc.accept(Unknown Source:2)
	at j$.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:1)
	at j$.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:2)
	at j$.util.Iterator$-CC.$default$forEachRemaining(Iterator.java:3)
	at j$.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:5)
	at j$.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:2)
	at j$.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:2)
	at j$.util.Iterator$-CC.$default$forEachRemaining(Iterator.java:3)
	at j$.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:5)
	at j$.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:6)
	at j$.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:3)
	at j$.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:5)
	at j$.util.stream.ReferencePipeline.collect(ReferencePipeline.java:17)
	at org.tosl.coronawarncompanion.dkdownload.DKDownloadUtils.lambda$getDKsForCountries$5(DKDownloadUtils.java:65)
	at org.tosl.coronawarncompanion.dkdownload.-$$Lambda$DKDownloadUtils$S15iCLvRKIHnwIFR2_4fy3RkZ00.apply(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:111)
	at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:437)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onComplete(ObservableConcatMap.java:527)
	at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
	at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
	at io.reactivex.internal.operators.mixed.MaybeFlatMapObservable$FlatMapObserver.onComplete(MaybeFlatMapObservable.java:79)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:437)`

Maybe there are too many keys in the last weeks to fit into Memory.

**Comment by mh-** [comment]
Have you tried to limit the number of days? This might be a work-around.
In general, on many devices the full key download still works (but they might have more RAM than your device). It then takes very long to match, though.
So limiting the number of days could help with both memory consumption and matching time.

**Comment by Romern** [comment]
I just saw the update, it doesnt crash anymore. Thank you very much!
