### ISSUE TITLE
Crash when an empty RaMBLE database is found

### ISSUE THREAD

**Issue by mh-** [mh-/corona-warn-companion-android#21]
(empty as in "contains no GAEN RPI")

Todo: Test what happens when an empty RaMBLE database is found.

**Comment by mh-** [comment]
Result is a crash 
```
Caused by: java.util.NoSuchElementException
        at java.util.TreeMap.key(TreeMap.java:1328)
        at java.util.TreeMap.firstKey(TreeMap.java:291)
        at java.util.TreeMap$KeySet.first(TreeMap.java:1144)
        at org.tosl.coronawarncompanion.MainActivity.onCreate(MainActivity.java:285)
```
in
```
            minDate = new Date(getMillisFromDays(rpiListDaysSinceEpochLocalTZ.first()));
```
