### ISSUE TITLE
App start-loops when enabling microg without having su

### ISSUE THREAD

**Issue by tlambertz** [mh-/corona-warn-companion-android#66]
First, let me thank you for this amazing app!

I am on an unrooted phone. When I open the app and select microg, the app does not open, and logcat shows an endless loop of the app opening, doing `su`, requesting the database, crashing, opening, ....

The only way out is to delete all app-data in android settings.

## Logcat output

```
10-20 14:41:21.152  8077  8077 D MicroGDbOnDisk: Trying to copy microG database
10-20 14:41:21.156  8077  8077 W System.err: java.io.IOException: Cannot run program "su": error=2, No such file or directory
10-20 14:41:21.158  8077  8077 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
10-20 14:41:21.158  8077  8077 W System.err: 	at java.lang.Runtime.exec(Runtime.java:699)
10-20 14:41:21.158  8077  8077 W System.err: 	at java.lang.Runtime.exec(Runtime.java:529)
10-20 14:41:21.158  8077  8077 W System.err: 	at java.lang.Runtime.exec(Runtime.java:426)
10-20 14:41:21.158  8077  8077 W System.err: 	at org.tosl.coronawarncompanion.gmsreadout.Sudo.sudo(Sudo.java:45)
10-20 14:41:21.158  8077  8077 W System.err: 	at org.tosl.coronawarncompanion.microgreadout.MicroGDbOnDisk.copyFromGMS(MicroGDbOnDisk.java:70)
10-20 14:41:21.158  8077  8077 W System.err: 	at org.tosl.coronawarncompanion.microgreadout.MicroGDbOnDisk.getRpisFromContactDB(MicroGDbOnDisk.java:94)
10-20 14:41:21.158  8077  8077 W System.err: 	at org.tosl.coronawarncompanion.MainActivity.onCreate(MainActivity.java:318)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.app.Activity.performCreate(Activity.java:8000)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.app.Activity.performCreate(Activity.java:7984)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.os.Looper.loop(Looper.java:223)
10-20 14:41:21.158  8077  8077 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-20 14:41:21.158  8077  8077 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-20 14:41:21.158  8077  8077 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-20 14:41:21.158  8077  8077 W System.err: 	at com.android.internal.os.ExecInit.main(ExecInit.java:43)
10-20 14:41:21.158  8077  8077 W System.err: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-20 14:41:21.158  8077  8077 W System.err: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
10-20 14:41:21.158  8077  8077 W System.err: Caused by: java.io.IOException: error=2, No such file or directory
10-20 14:41:21.158  8077  8077 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
10-20 14:41:21.158  8077  8077 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
10-20 14:41:21.158  8077  8077 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
10-20 14:41:21.158  8077  8077 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
10-20 14:41:21.158  8077  8077 W System.err: 	... 24 more
10-20 14:41:21.158  8077  8077 D MicroGDbOnDisk: Result from trying to copy LevelDB: 
10-20 14:41:21.158  8077  8077 E MicroGDbOnDisk: ERROR: Super User rights not granted!
10-20 14:41:21.160  8077  8077 E SQLiteLog: (14) cannot open file at line 38589 of [b2325a6e1c]
10-20 14:41:21.160  8077  8077 E SQLiteLog: (14) os_unix.c:38589: (2) open(/storage/emulated/10/Android/data/org.tosl.warnappcompanion/cache/exposure.db_) - 
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: Failed to open database '/storage/emulated/10/Android/data/org.tosl.warnappcompanion/cache/exposure.db_'.
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/storage/emulated/10/Android/data/org.tosl.warnappcompanion/cache/exposure.db_': File /storage/emulated/10/Android/data/org.tosl.warnappcompanion/cache/exposure.db_ doesn't exist
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:252)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:789)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:736)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at org.tosl.coronawarncompanion.microgreadout.MicroGDbOnDisk.getRpisFromContactDB(MicroGDbOnDisk.java:96)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at org.tosl.coronawarncompanion.MainActivity.onCreate(MainActivity.java:318)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.app.Activity.performCreate(Activity.java:8000)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.app.Activity.performCreate(Activity.java:7984)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.os.Looper.loop(Looper.java:223)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at java.lang.reflect.Method.invoke(Native Method)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at com.android.internal.os.ExecInit.main(ExecInit.java:43)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
10-20 14:41:21.166  8077  8077 E SQLiteDatabase: 	... 27 more
10-20 14:41:21.166  8077  8077 W System.err: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/storage/emulated/10/Android/data/org.tosl.warnappcompanion/cache/exposure.db_': File /storage/emulated/10/Android/data/org.tosl.warnappcompanion/cache/exposure.db_ doesn't exist
10-20 14:41:21.166  8077  8077 W System.err: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:252)
10-20 14:41:21.166  8077  8077 W System.err: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
10-20 14:41:21.166  8077  8077 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
10-20 14:41:21.166  8077  8077 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
10-20 14:41:21.166  8077  8077 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
10-20 14:41:21.166  8077  8077 W System.err: 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
10-20 14:41:21.166  8077  8077 W System.err: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
10-20 14:41:21.166  8077  8077 W System.err: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:789)
10-20 14:41:21.166  8077  8077 W System.err: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:736)
10-20 14:41:21.166  8077  8077 W System.err: 	at org.tosl.coronawarncompanion.microgreadout.MicroGDbOnDisk.getRpisFromContactDB(MicroGDbOnDisk.java:96)
10-20 14:41:21.166  8077  8077 W System.err: 	at org.tosl.coronawarncompanion.MainActivity.onCreate(MainActivity.java:318)
10-20 14:41:21.166  8077  8077 W System.err: 	at android.app.Activity.performCreate(Activity.java:8000)
10-20 14:41:21.166  8077  8077 W System.err: 	at android.app.Activity.performCreate(Activity.java:7984)
10-20 14:41:21.166  8077  8077 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
10-20 14:41:21.167  8077  8077 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
10-20 14:41:21.167  8077  8077 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
10-20 14:41:21.167  8077  8077 W System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
10-20 14:41:21.167  8077  8077 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-20 14:41:21.167  8077  8077 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-20 14:41:21.167  8077  8077 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
10-20 14:41:21.167  8077  8077 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-20 14:41:21.167  8077  8077 W System.err: 	at android.os.Looper.loop(Looper.java:223)
10-20 14:41:21.167  8077  8077 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-20 14:41:21.167  8077  8077 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-20 14:41:21.167  8077  8077 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-20 14:41:21.167  8077  8077 W System.err: 	at com.android.internal.os.ExecInit.main(ExecInit.java:43)
10-20 14:41:21.167  8077  8077 W System.err: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-20 14:41:21.167  8077  8077 W System.err: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
10-20 14:41:21.167  8077  8077 W System.err: Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
10-20 14:41:21.167  8077  8077 W System.err: 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
10-20 14:41:21.167  8077  8077 W System.err: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
10-20 14:41:21.167  8077  8077 W System.err: 	... 27 more
10-20 14:41:21.175  8077  8077 D AndroidRuntime: Shutting down VM
10-20 14:41:21.176  8077  8077 E AndroidRuntime: FATAL EXCEPTION: main
10-20 14:41:21.176  8077  8077 E AndroidRuntime: Process: org.tosl.warnappcompanion, PID: 8077
10-20 14:41:21.176  8077  8077 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tosl.warnappcompanion/org.tosl.coronawarncompanion.MainActivity}: java.lang.IllegalStateException
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
10-20 14:41:21.176  8077  80710-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at org.tosl.coronawarncompanion.MainActivity.showExtractionError(MainActivity.java:410)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at org.tosl.coronawarncompanion.MainActivity.onCreate(MainActivity.java:361)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8000)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7984)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	... 13 more
10-20 14:41:21.176  8077  8077 E AndroidRuntime: Error reporting crash
10-20 14:41:21.176  8077  8077 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:540)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5182)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:158)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
10-20 14:41:21.176  8077  8077 I Process : Sending signal. PID: 8077 SIG: 9
10-20 14:41:21.219  1016 10400 I ActivityManager: Process org.tosl.warnappcompanion (pid 8077) has died: fg  TOP 
7 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:43)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: Caused by: java.lang.IllegalStateException
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at org.tosl.coronawarncompanion.MainActivity.showExtractionError(MainActivity.java:410)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at org.tosl.coronawarncompanion.MainActivity.onCreate(MainActivity.java:361)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8000)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7984)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	... 13 more
10-20 14:41:21.176  8077  8077 E AndroidRuntime: Error reporting crash
10-20 14:41:21.176  8077  8077 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:540)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5182)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:158)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-20 14:41:21.176  8077  8077 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
10-20 14:41:21.176  8077  8077 I Process : Sending signal. PID: 8077 SIG: 9
10-20 14:41:21.219  1016 10400 I ActivityManager: Process org.tosl.warnappcompanion (pid 8077) has died: fg  TOP 

```

**Comment by mh-** [comment]
@tlambertz Release 1.3.9 https://github.com/mh-/corona-warn-companion-android/releases/tag/1.3.9 should fix this issue - basically I forgot to add `MICROG_MODE` in one place, which caused a `java.lang.IllegalStateException` - it would be great if you could verify that this is fixed now.

**Comment by tlambertz** [comment]
Oh sorry I have missed this. The new release fixed the issue :)

**Comment by mh-** [comment]
Ok, thanks
