### ISSUE TITLE
One Download Error for England and Wales

### ISSUE THREAD

**Issue by mh-** [mh-/corona-warn-companion-android#81]
```
D/DKDownloadEAW: Downloaded daily: 2020102400.zip
D/Unzip: Unzipped file. Length: 402204
D/DKDownloadUtils: Number of keys in this file: 12565
D/DKDownloadEAW: Downloaded daily: 2020110200.zip
D/Unzip: Unzipped file. Length: 491068
I/nawarncompanio: Background concurrent copying GC freed 106415(7MB) AllocSpace objects, 7(428KB) LOS objects, 19% free, 24MB/30MB, paused 151us total 314.110ms
D/DKDownloadUtils: Number of keys in this file: 15342
D/DKDownloadEAW: Downloaded daily: 2020102300.zip
D/Unzip: Unzipped file. Length: 278908
D/DKDownloadUtils: Number of keys in this file: 8712
D/DKDownloadEAW: Downloaded daily: 2020103100.zip
D/Unzip: Unzipped file. Length: 550972
D/DKDownloadUtils: Number of keys in this file: 17214
D/DKDownloadEAW: Downloaded daily: 2020102200.zip
D/Unzip: Unzipped file. Length: 203644
D/DKDownloadUtils: Number of keys in this file: 6360
D/DKDownloadEAW: Downloaded daily: 2020102100.zip
D/Unzip: Unzipped file. Length: 127804
D/DKDownloadUtils: Number of keys in this file: 3990
I/nawarncompanio: Background concurrent copying GC freed 90856(5MB) AllocSpace objects, 24(5MB) LOS objects, 17% free, 28MB/34MB, paused 145us total 225.032ms
D/DKDownloadEAW: Downloaded daily: 2020102000.zip
D/Unzip: Unzipped file. Length: 220
D/DKDownloadUtils: Number of keys in this file: 3
W/System.err: retrofit2.adapter.rxjava2.HttpException: HTTP 403 
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
W/System.err:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
        at io.reactivex.Maybe.subscribe(Maybe.java:4262)
        at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
D/DKDownloadEAW: Downloaded daily: 2020110100.zip
D/Unzip: Unzipped file. Length: 556892
D/DKDownloadUtils: Number of keys in this file: 17399
D/ViewRootImpl[Toast]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
D/Surface: Surface::allocateBuffers(this=0x7746b33000)
D/Surface: Surface::connect(this=0x7746b33000,api=1)
I/nawarncompanio: Background concurrent copying GC freed 43557(2MB) AllocSpace objects, 39(6MB) LOS objects, 18% free, 27MB/33MB, paused 115us total 289.349ms
D/DKDownloadEAW: Downloaded daily: 2020102600.zip
D/Unzip: Unzipped file. Length: 463996
D/DKDownloadUtils: Number of keys in this file: 14496
D/DKDownloadEAW: Downloaded daily: 2020102900.zip
D/Unzip: Unzipped file. Length: 557276
D/DKDownloadUtils: Number of keys in this file: 17411
D/DKDownloadEAW: Downloaded daily: 2020102800.zip
D/Unzip: Unzipped file. Length: 657212
D/DKDownloadUtils: Number of keys in this file: 20534
D/DKDownloadEAW: Downloaded daily: 2020102700.zip
D/Unzip: Unzipped file. Length: 556572
I/nawarncompanio: Background concurrent copying GC freed 21088(2MB) AllocSpace objects, 13(4MB) LOS objects, 11% free, 44MB/50MB, paused 511us total 290.329ms
D/DKDownloadUtils: Number of keys in this file: 17389
D/DKDownloadEAW: Downloaded daily: 2020103000.zip
D/Unzip: Unzipped file. Length: 588380
D/DKDownloadUtils: Number of keys in this file: 18383
D/DKDownloadEAW: Downloaded daily: 2020102500.zip
D/Unzip: Unzipped file. Length: 444380
D/DKDownloadUtils: Number of keys in this file: 13883
D/DKDownloadEAW: Download two-hourly: 2020110202.zip
D/Unzip: Unzipped file. Length: 11452
D/DKDownloadUtils: Number of keys in this file: 354
I/nawarncompanio: Background concurrent copying GC freed 73925(3MB) AllocSpace objects, 38(10MB) LOS objects, 12% free, 41MB/47MB, paused 180us total 379.775ms
D/DKDownloadEAW: Download two-hourly: 2020110206.zip
D/Unzip: Unzipped file. Length: 5436
D/DKDownloadUtils: Number of keys in this file: 166
D/DKDownloadEAW: Download two-hourly: 2020110204.zip
D/Unzip: Unzipped file. Length: 6044
D/DKDownloadUtils: Number of keys in this file: 185
D/MainActivity: Number of keys that have been downloaded: 184386
I/nawarncompanio: Background concurrent copying GC freed 146390(6MB) AllocSpace objects, 17(4MB) LOS objects, 13% free, 37MB/43MB, paused 111us total 387.909ms
D/Matcher: Started matching...
```
@kbobrowski @benjeffery FYI

**Comment by mh-** [comment]
Today, 2020-11-02:
```
% curl -H 'Host: distribution-te-prod.prod.svc-test-trace.nhs.uk' -H 'user-agent: okhttp/3.14.9' --compressed 'https://distribution-te-prod.prod.svc-test-trace.nhs.uk/distribution/daily/2020101900.zip'
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>BH2NDQ2K4JAH2J6G</RequestId><HostId>fbdoIQjHLM4NzoRPCwUz1u+1yUH63j/D2GOftywbOeTDVEFRd9sZD8Z3aNKtWlOrealBHd2GkX4=</HostId></Error>
```
So today minus 14 days is not available / access denied.
@benjeffery, can you confirm that?

**Comment by kbobrowski** [comment]
This error is because I did not make any assumption on retention of DKs, and just try to download from min date which is passed to the method. This is last 15 days, but actual retention on NHS servers is 14 days. Unfortunately there seem to be no index available on NHS server. We can ignore min date and just download last 14 days

**Comment by benjeffery** [comment]
> @benjeffery, can you confirm that?

Yes I can confirm that's what I am seeing too. It also is consistent with their documentation here: https://www.gov.uk/government/publications/nhs-covid-19-app-privacy-information/anonymisation-definitions-and-user-data-journeys

"The app will hold details of a relevant test result but only for as long as necessary, 14 days after any self-isolation period this data is no longer recorded."
