### ISSUE TITLE
Crash on API 30 (Android R)

### ISSUE THREAD

**Issue by mh-** [mh-/corona-warn-companion-android#9]
App version 1.0.6 crashes:

```
D/ContactDbOnDisk: Trying to copy LevelDB
W/ContextImpl: Failed to ensure /storage/emulated/0/Android/data/org.tosl.warnappcompanion/cache: android.os.ServiceSpecificException:  (code -1)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tosl.warnappcompanion, PID: 5266
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tosl.warnappcompanion/org.tosl.coronawarncompanion.MainActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:220)
        at org.tosl.coronawarncompanion.gmsreadout.ContactDbOnDisk.copyFromGMS(ContactDbOnDisk.java:65)
        at org.tosl.coronawarncompanion.gmsreadout.ContactDbOnDisk.getRpisFromContactDB(ContactDbOnDisk.java:218)
        at org.tosl.coronawarncompanion.MainActivity.onCreate(MainActivity.java:205)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

Code:
```
        Log.d(TAG, "Trying to copy LevelDB");
        String cachePathStr = Objects.requireNonNull(context.getExternalCacheDir()).getPath();
```

**Comment by mh-** [comment]
Apparently the device emulator doesn't emulate an SD card? 
Anyway, the problem was that `getExternalCacheDir()` returns `null`. However, `getCacheDir()`works fine.
